
/*
 * 
 */

package ud.ing.modi.pago;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.2
 * Sun Aug 30 17:19:49 COT 2015
 * Generated source version: 2.1.2
 * 
 */


@WebServiceClient(name = "PagoComprasImpService", 
                  wsdlLocation = "classpath:/wsdl/pagoCompras.wsdl",
                  targetNamespace = "http://pago.modi.ing.ud/") 
public class PagoComprasImpService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://pago.modi.ing.ud/", "PagoComprasImpService");
    public final static QName PagoComprasImpPort = new QName("http://pago.modi.ing.ud/", "PagoComprasImpPort");
    static {
        URL url = null;
        
        url = PagoComprasImpService.class.getClassLoader().getResource("/wsdl/pagoCompras.wsdl");
        if (url == null) {
            url = PagoComprasImpService.class.getClassLoader().getResource("wsdl/pagoCompras.wsdl");
        }
        if (url == null) {
            System.err.println("Can not initialize the default wsdl from classpath:/wsdl/pagoCompras.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PagoComprasImpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PagoComprasImpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PagoComprasImpService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns PagoCompras
     */
    @WebEndpoint(name = "PagoComprasImpPort")
    public PagoCompras getPagoComprasImpPort() {
        return super.getPort(PagoComprasImpPort, PagoCompras.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PagoCompras
     */
    @WebEndpoint(name = "PagoComprasImpPort")
    public PagoCompras getPagoComprasImpPort(WebServiceFeature... features) {
        return super.getPort(PagoComprasImpPort, PagoCompras.class, features);
    }

}
